services:
  twicas-monitoring:
    build:
      context: ./containers/puppeteer
    image: twicas-monitoring:latest
    container_name: twicas-monitoring
    hostname: twicas-monitoring
    command: ["npm", "run", "start"]
    environment:
      - USER_AGENT
      - YOUTUBE_TEST_URL
      - OPENSEARCH_URL
      - OPENSEARCH_USER
      - OPENSEARCH_PASSWORD
      - DOWNLOAD_DIR
      - LOG_DIR
      - RABBITMQ_URL
      - RABBITMQ_PORT
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD

  # twicas-flask:
  #   build:
  #     context: ./containers/flask
  #   image: twicas-flask:latest
  #   container_name: twicas-flask
  #   hostname: twicas-flask
  #   environment:
  #     - TOKEN
  #     - DB_FILE_PATH
  #   ports:
  #     - "5000:5000"

  # ffmpeg:
  #   build:
  #     context: ./containers/ffmpeg
  #   image: ffmpeg:latest
  #   container_name: ffmpeg
  #   hostname: ffmpeg
  #   volumes:
  #     - ./containers/ffmpeg/data:/data
  #   tty: true
  #   entrypoint: bash

  twicas-publisher:
    build:
      context: ./containers/publisher
    image: twicas-publisher:latest
    container_name: twicas-publisher
    hostname: twicas-publisher
    command: ["npm", "run", "start"]
    environment:
      - RABBITMQ_URL
      - RABBITMQ_PORT
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - PORT_NUM
    ports:
      - "18080:18080"

networks:
  default:
    name: twicas
