services:
  twicas:
    build:
      context: .
    image: twicas:latest
    container_name: twicas
    hostname: twicas
    volumes:
      - ./playwright:/playwright
    tty: true
    entrypoint: bash

networks:
  default:
    name: twicas
